// Generated by tools/generate-template-outputs.mjs. Do not edit directly.
const LABELSPRINT_TEMPLATES = Object.freeze({
  "4331": createWorkspaceTemplate_("4331", "Avery 4331", "Specialty", "Large labels, 15 per sheet", 2.625, 2, 5, 3, 0.5, 0.1875, 0.125, 0, []),
  "5126": createWorkspaceTemplate_("5126", "Avery 5126 / 8126", "Shipping", "Half-sheet shipping labels, 2 per sheet", 8.5, 5.5, 2, 1, 0, 0, 0, 0, ["8126"]),
  "5160": createWorkspaceTemplate_("5160", "Avery 5160 / 8160", "Address", "Address labels, 30 per sheet", 2.625, 1, 10, 3, 0.5, 0.1875, 0.125, 0, ["5260","55160","5520","5630","5960","5970","8160","8250","8460","8660","18160","18660","16460"]),
  "5161": createWorkspaceTemplate_("5161", "Avery 5161 / 8161", "Address", "Address labels, 20 per sheet", 4, 1, 10, 2, 0.5, 0.15625, 0.1875, 0, ["5261","5961","8161"]),
  "5162": createWorkspaceTemplate_("5162", "Avery 5162 / 8162", "Address", "Address labels, 14 per sheet", 4, 1.333333, 7, 2, 0.833333, 0.25, 0, 0, ["5262","5962","8162","48862"]),
  "5163": createWorkspaceTemplate_("5163", "Avery 5163 / 8163", "Shipping", "Shipping labels, 10 per sheet", 4, 2, 5, 2, 0.5, 0.25, 0, 0, ["5263","5663","5963","8163","18163","48363"]),
  "5164": createWorkspaceTemplate_("5164", "Avery 5164 / 8164", "Shipping", "Shipping labels, 6 per sheet", 4, 3.333333, 3, 2, 0.5, 0.25, 0, 0, ["5264","5664","8164"]),
  "5167": createWorkspaceTemplate_("5167", "Avery 5167 / 8167", "Return", "Return address labels, 80 per sheet", 1.75, 0.5, 20, 4, 0.5, 0.28125, 0.3125, 0, ["5267","5667","8167","11408","11410","11452","16062"]),
  "5168": createWorkspaceTemplate_("5168", "Avery 5168 / 8168", "Shipping", "Large shipping labels, 4 per sheet", 3.5, 5, 2, 2, 0.5, 0.75, 0, 0, ["5268","8168"]),
  "5195": createWorkspaceTemplate_("5195", "Avery 5195 / 8195", "Return", "Return address labels, 60 per sheet", 1.75, 0.666667, 15, 4, 0.5, 0.28125, 0.3125, 0, ["8195","18195"]),
  "5302": createWorkspaceTemplate_("5302", "Avery 5302", "Cards", "Small tent cards, 4 per sheet", 3.5, 2, 2, 2, 3.5, 0.75, 0, 0, ["5812","5913"]),
  "5305": createWorkspaceTemplate_("5305", "Avery 5305", "Cards", "Full-width cards, 4 per sheet", 8.5, 2.5, 4, 1, 0.5, 0, 0, 0, []),
  "5360": createWorkspaceTemplate_("5360", "Avery 5360", "File Folder", "File folder labels, 21 per sheet", 2.8125, 1.5, 7, 3, 0.25, 0.03125, 0, 0, ["55360"]),
  "5366": createWorkspaceTemplate_("5366", "Avery 5366", "File Folder", "File folder labels, 30 per sheet", 3.4375, 0.666667, 15, 2, 0.5, 0.8125, 0, 0, ["5266","8366","48366"]),
  "5371": createWorkspaceTemplate_("5371", "Avery 5371 / 8371", "Cards", "Business cards, 10 per sheet", 3.5, 2, 5, 2, 0.5, 0.75, 0, 0, ["28371","8371","8387","8871","38873","38876"]),
  "5392": createWorkspaceTemplate_("5392", "Avery 5392", "Badges", "Name badge insert refills, 6 per sheet", 4, 3, 3, 2, 1, 0.25, 0, 0, ["35392","5384","5393","74459","74536","74540","74541","78617","78619","8780","8781"]),
  "5395": createWorkspaceTemplate_("5395", "Avery 5395", "Badges", "Name badges, 8 per sheet", 3.375, 2.333333, 4, 2, 0.833333, 0.6875, 0.375, 0, ["8395"]),
  "7714": createWorkspaceTemplate_("7714", "Avery 7714", "Specialty", "Small labels, 36 per sheet", 2, 0.5, 18, 2, 1, 2.25, 0, 0, ["07714","11984","23281"]),
  "11102": createWorkspaceTemplate_("11102", "Avery 11102", "Specialty", "Small labels, 52 per sheet", 1.5, 0.333333, 26, 2, 1.166667, 2.75, 0, 0, []),
  "11270": createWorkspaceTemplate_("11270", "Avery 11270", "Specialty", "Small labels, 52 per sheet", 2, 0.333333, 26, 2, 1.1708, 2.25, 0, 0, []),
  "11401": createWorkspaceTemplate_("11401", "Avery 11401", "Specialty", "Small labels, 40 per sheet", 1.5, 0.5, 20, 2, 0.5, 2.75, 0, 0, ["11836"]),
  "11415": createWorkspaceTemplate_("11415", "Avery 11415", "Specialty", "Small labels, 80 per sheet", 1.125, 0.5, 20, 4, 0.5, 0.5104, 1, 0, ["11433","11991","11995"]),
  "22806": createWorkspaceTemplate_("22806", "Avery 22806", "Specialty", "Square labels, 12 per sheet", 2, 2, 4, 3, 0.75, 1.125, 0.125, 0.125, ["22807"]),
  "22816": createWorkspaceTemplate_("22816", "Avery 22816", "Specialty", "Round or specialty labels, 12 per sheet", 2, 2, 4, 3, 0.625, 0.625, 0.625, 0.5826, ["22923","22933","22961","41467"]),
  "22926": createWorkspaceTemplate_("22926", "Avery 22926", "Specialty", "Round or specialty labels, 9 per sheet", 2.5, 2.5, 3, 3, 0.625, 0.3229, 0.1771, 1.1146, []),
  "22964": createWorkspaceTemplate_("22964", "Avery 22964", "Specialty", "Specialty labels, 8 per sheet", 3.3333, 2, 4, 2, 1.0125, 0.75, 0.3334, 0.3542, []),
  "38373": createWorkspaceTemplate_("38373", "Avery 38373", "Cards", "Cards, 8 per sheet", 3.5, 2, 4, 2, 0.75, 0.5, 0.5, 0.5, ["18820"]),
  "94224": createWorkspaceTemplate_("94224", "Avery 94224", "Specialty", "Rectangle labels, 16 per sheet", 3, 1, 8, 2, 0.625, 0.875, 0.75, 0.25, [])
});

function createWorkspaceTemplate_(id, name, category, description, widthIn, heightIn, rows, columns, topIn, leftIn, horizontalGapIn, verticalGapIn, aliases) {
  return Object.freeze({
    id: id,
    name: name,
    category: category,
    description: description,
    widthIn: widthIn,
    heightIn: heightIn,
    rows: rows,
    columns: columns,
    topIn: topIn,
    leftIn: leftIn,
    horizontalGapIn: horizontalGapIn,
    verticalGapIn: verticalGapIn,
    aliases: aliases || [],
    labelsPerSheet: rows * columns
  });
}

function getWorkspaceTemplate_(templateId) {
  const normalized = String(templateId || '').replace(/\D/g, '');
  if (LABELSPRINT_TEMPLATES[normalized]) return LABELSPRINT_TEMPLATES[normalized];

  const ids = Object.keys(LABELSPRINT_TEMPLATES);
  for (let index = 0; index < ids.length; index += 1) {
    const template = LABELSPRINT_TEMPLATES[ids[index]];
    if (template.aliases.indexOf(normalized) >= 0) return template;
  }

  return LABELSPRINT_TEMPLATES['5160'];
}
